# Generated by Django 6.0.2 on 2026-02-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book_price_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='Fiction', max_length=200),
        ),
    ]
