# Generated by Django 6.0.1 on 2026-01-26 12:44

import firstdjango.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.TextField(default=models.CharField(max_length=200)),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=firstdjango.models.current_year),
        ),
    ]
