# Generated by Django 6.0.1 on 2026-01-26 12:44

import django.core.validators
import firstdjango.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0002_author_genre_book_price_book_synopsis_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=firstdjango.models.current_year, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
