# Generated by Django 6.0.1 on 2026-01-26 12:45

import django.core.validators
import firstdjango.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0003_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=firstdjango.models.current_year, validators=[django.core.validators.MinValueValidator(1000), firstdjango.models.max_value_current_year]),
        ),
    ]
