# Generated by Django 6.0.1 on 2026-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0004_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.CharField(default='True', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Fiction', max_length=100),
        ),
    ]
