# Generated by Django 6.0.1 on 2026-02-03 15:15

import django.core.validators
import firstdjango.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstdjango', '0005_author_created_by_alter_author_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='out_of_print',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=firstdjango.models.current_year, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
